[package]

name = "ascii"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]

[dependencies]
winapi = "*"
kernel32-sys = "*"
image = { version = "*", features = ["png_codec"], default-features = false }
nalgebra = "0.2"
rand = "*"
