[package]

name = "ascii"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]

[dependencies]
winapi = "*"
kernel32-sys = "*"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"
